{
 "title": "Kube-burner2",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "elasticsearch" },
   {
    "name": "workload",
    "label": "Workload",
    "query": "{\"find\": \"terms\", \"field\": \"jobConfig.name.keyword\"}"
   },
   {
    "name": "uuid",
    "label": "UUID",
    "query": "{\"find\": \"terms\", \"field\": \"uuid.keyword\", \"query\": \"jobConfig.name.keyword: $workload\"}"
   },
   {
    "name": "master",
    "label": "Master nodes",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.node.keyword\", \"query\": \"metricName.keyword: nodeRoles AND labels.role.keyword: master AND uuid.keyword: $uuid\"}"
   },
   {
    "name": "worker",
    "label": "Worker nodes",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.node.keyword\", \"query\": \"metricName.keyword: nodeRoles AND labels.role.keyword: worker AND uuid.keyword: $uuid\"}"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "jobStart",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "versi",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_data"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: jobSummary AND jobConfig.name :network-policy-perf",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "k8s minor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"k8sVersion\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "max" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"felix_cluster_num_hosts\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "netpol config",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Namespaces",
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"convergence_tracker_info\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: jobSummary",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Iptables rules",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "iptables_filter_rules", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"convergence_tracker\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Ipset length",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "ipsets_list_len", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"convergence_tracker\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Calico Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Calico node cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:329",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:159",
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "labels.namespace.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerCPU\" AND labels.container.keyword: calico-node",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Calico node memory usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:329",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:159",
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "labels.namespace.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": { "script": "_value / 1000000" },
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerMemory\" AND labels.container.keyword: calico-node",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Active local endpoints",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "labels.kubernetes_io_hostname.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"felix_active_local_endpoints\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Label index endpoints",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "labels.kubernetes_io_hostname.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"felix_label_index_num_endpoints\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Active local policies",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "labels.kubernetes_io_hostname.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"felix_active_local_policies\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Label index optimised selectors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "labels.kubernetes_io_hostname.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"felix_label_index_num_active_selectors_optimized\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Active local selectors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "labels.kubernetes_io_hostname.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"felix_active_local_selectors\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Label index unoptimised selectors ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "labels.kubernetes_io_hostname.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"felix_label_index_num_active_selectors_not_optimized\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Cluster status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Kube-apiserver usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:329",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:159",
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "labels.namespace.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerCPU\" AND labels.container.keyword: kube-apiserver",
     "timeField": "timestamp"
    },
    {
     "alias": "Rss {{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:329",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:159",
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "labels.namespace.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerMemory\" AND labels.container.keyword: kube-apiserver",
     "timeField": "timestamp"
    },
    {
     "alias": "Rss {{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:329",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:159",
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "labels.namespace.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerMemory-Masters\" AND labels.container.keyword: kube-apiserver",
     "timeField": "timestamp"
    },
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:329",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:159",
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "labels.namespace.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerCPU-Masters\" AND labels.container.keyword: kube-apiserver",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Average kube-apiserver usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Avg CPU kube-apiserver",
     "bucketAggs": [
      {
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.container.keyword: kube-apiserver",
     "timeField": "timestamp"
    },
    {
     "alias": "Avg Rss kube-apiserver",
     "bucketAggs": [
      {
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.container.keyword: kube-apiserver",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Active Kube-controller-manager usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:329",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:159",
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "labels.namespace.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerCPU\" AND labels.container.keyword: kube-controller-manager",
     "timeField": "timestamp"
    },
    {
     "alias": "Rss {{labels.namespace.keyword}}-{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:329",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:159",
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "labels.namespace.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerMemory\" AND labels.container.keyword: kube-controller-manager",
     "timeField": "timestamp"
    },
    {
     "alias": "{{labels.namespace.keyword}}-{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:329",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:159",
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "labels.namespace.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerCPU-Masters\" AND labels.container.keyword: kube-controller-manager",
     "timeField": "timestamp"
    },
    {
     "alias": "Rss {{labels.namespace.keyword}}-{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:329",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:159",
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "labels.namespace.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerMemory-Masters\" AND labels.container.keyword: kube-controller-manager",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Kube-scheduler usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:329",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:159",
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "labels.namespace.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.container.keyword: kube-scheduler",
     "timeField": "timestamp"
    },
    {
     "alias": "Rss {{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:329",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:159",
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "labels.namespace.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.container.keyword: kube-scheduler",
     "timeField": "timestamp"
    },
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:329",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:159",
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "labels.namespace.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU-Masters\" AND labels.container.keyword: kube-scheduler",
     "timeField": "timestamp"
    },
    {
     "alias": "Rss {{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:329",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:159",
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "labels.namespace.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory-Masters\" AND labels.container.keyword: kube-scheduler",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}