{
 "title": "Kube-burner Report - Raw UUID",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "elasticsearch" },
   {
    "name": "workload",
    "label": "Workload",
    "query": "{\"find\": \"terms\", \"field\": \"jobConfig.name.keyword\"}"
   },
   {
    "name": "uuid",
    "label": "UUID",
    "query": "{\"find\": \"terms\", \"field\": \"uuid.keyword\", \"query\": \"jobConfig.name.keyword: $workload\"}"
   },
   {
    "name": "master",
    "label": "Master nodes",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.node.keyword\", \"query\": \"metricName.keyword: nodeRoles AND labels.role.keyword: master AND uuid.keyword: $uuid\"}"
   },
   {
    "name": "worker",
    "label": "Worker nodes",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.node.keyword\", \"query\": \"metricName.keyword: nodeRoles AND labels.role.keyword: worker AND uuid.keyword: $uuid\"}"
   },
   {
    "name": "infra",
    "label": "Infra nodes",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.node.keyword\",  \"query\": \"metricName.keyword: nodeRoles AND labels.role.keyword: infra AND uuid.keyword: $uuid\"}"
   },
   { "name": "latencyPercentile", "label": "Latency percentile", "query": "P99, P95, P50" }
  ]
 },
 "panels": [
  {
   "title": "Node count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4404",
       "fake": true,
       "field": "labels.role.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "coun",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"nodeRoles\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "pods",
     "bucketAggs": [
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"podCount\"",
     "timeField": "timestamp"
    },
    {
     "alias": "namespaces",
     "bucketAggs": [
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"namespaceCount\"",
     "timeField": "timestamp"
    },
    {
     "alias": "netpolIngress",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"netpolIngressCount\"",
     "timeField": "timestamp"
    },
    {
     "alias": "netpolEgress",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"netpolEgressCount\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "jobStart",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "versi",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_data"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: jobSummary AND jobConfig.name :network-policy-perf",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "OCP version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"clusterVersion\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "k8s minor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"k8sVersion\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Etcd version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "versi",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_data"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"etcdVersion\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "netpol config",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Namespaces",
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"convergence_tracker_info\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: jobSummary",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "convergence results",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "metrics": [
      { "id": "3", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"convergence_tracker\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Cluster status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alerts",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: alert",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Masters CPU utilization",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{labels.instance.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:133",
         "fake": true,
         "field": "labels.instance.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "settings": { "script": "_value * 100" }, "type": "sum" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeCPU-Masters\" AND NOT labels.mode.keyword: idle AND NOT labels.mode.keyword: steal",
       "timeField": "timestamp"
      },
      {
       "alias": "Aggregated",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "settings": { "script": "_value*100" }, "type": "sum" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: nodeCPU-Masters AND NOT labels.mode.keyword: idle AND NOT labels.mode.keyword: steal",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Masters Memory utilization",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "Utilization {{labels.instance.keyword}}",
       "bucketAggs": [
        {
         "field": "labels.instance.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: nodeMemoryUtilization-Masters",
       "timeField": "timestamp"
      },
      {
       "alias": "Total {{labels.instance.keyword}}",
       "bucketAggs": [
        {
         "field": "labels.instance.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: nodeMemoryTotal-Masters",
       "timeField": "timestamp"
      },
      {
       "alias": "Aggregated utilization",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "sum" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: nodeMemoryUtilization-Masters",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Node status summary",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:4404",
         "fake": true,
         "field": "labels.condition.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeStatus\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Pod status summary",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:4404",
         "fake": true,
         "field": "labels.phase.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"podStatusCount\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Kube-apiserver usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerCPU\" AND labels.container.keyword: kube-apiserver",
       "timeField": "timestamp"
      },
      {
       "alias": "Rss {{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerMemory\" AND labels.container.keyword: kube-apiserver",
       "timeField": "timestamp"
      },
      {
       "alias": "Rss {{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerMemory-Masters\" AND labels.container.keyword: kube-apiserver",
       "timeField": "timestamp"
      },
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerCPU-Masters\" AND labels.container.keyword: kube-apiserver",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Average kube-apiserver usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "Avg CPU kube-apiserver",
       "bucketAggs": [
        {
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.container.keyword: kube-apiserver",
       "timeField": "timestamp"
      },
      {
       "alias": "Avg Rss kube-apiserver",
       "bucketAggs": [
        {
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.container.keyword: kube-apiserver",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Active Kube-controller-manager usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerCPU\" AND labels.container.keyword: kube-controller-manager",
       "timeField": "timestamp"
      },
      {
       "alias": "Rss {{labels.namespace.keyword}}-{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerMemory\" AND labels.container.keyword: kube-controller-manager",
       "timeField": "timestamp"
      },
      {
       "alias": "{{labels.namespace.keyword}}-{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerCPU-Masters\" AND labels.container.keyword: kube-controller-manager",
       "timeField": "timestamp"
      },
      {
       "alias": "Rss {{labels.namespace.keyword}}-{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerMemory-Masters\" AND labels.container.keyword: kube-controller-manager",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Kube-scheduler usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.container.keyword: kube-scheduler",
       "timeField": "timestamp"
      },
      {
       "alias": "Rss {{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.container.keyword: kube-scheduler",
       "timeField": "timestamp"
      },
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerCPU-Masters\" AND labels.container.keyword: kube-scheduler",
       "timeField": "timestamp"
      },
      {
       "alias": "Rss {{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerMemory-Masters\" AND labels.container.keyword: kube-scheduler",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  { "title": "OVNKubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "ovnkube-master pods CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "sum" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.pod.keyword: /ovnkube-master.*/",
     "timeField": "timestamp"
    },
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "sum" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.pod.keyword: /ovnkube-control-plane.*/",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ovnkube-master pods Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "sum" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.pod.keyword: /ovnkube-master.*/ ",
     "timeField": "timestamp"
    },
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "sum" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.pod.keyword: /ovnkube-control-plane.*/ ",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ovnkube-master CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}-{{labels.container.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "labels.container.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.pod.keyword: /ovnkube-master.*/",
     "timeField": "timestamp"
    },
    {
     "alias": "{{labels.pod.keyword}}-{{labels.container.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "labels.container.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.pod.keyword: /ovnkube-control-plane.*/",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ovnkube-master Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}-{{labels.container.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "labels.container.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "sum" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.pod.keyword: /ovnkube-master.*/ ",
     "timeField": "timestamp"
    },
    {
     "alias": "{{labels.pod.keyword}}-{{labels.container.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "labels.container.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "sum" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.pod.keyword: /ovnkube-control-plane.*/ ",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ovnkube-node pods CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "sum" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.namespace.keyword: \"openshift-ovn-kubernetes\" AND labels.pod.keyword: /ovnkube-node.*/",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ovnkube-node pods Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "sum" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.namespace.keyword: \"openshift-ovn-kubernetes\"  AND labels.pod.keyword: /ovnkube-node.*/",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ovnkube-controller CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.namespace.keyword: \"openshift-ovn-kubernetes\"  AND labels.pod.keyword: /ovnkube-node.*/ AND labels.container.keyword: \"ovnkube-controller\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ovnkube-controller Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.namespace.keyword: \"openshift-ovn-kubernetes\"  AND labels.pod.keyword: /ovnkube-node.*/ AND labels.container.keyword: \"ovnkube-controller\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "nbdb CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.namespace.keyword: \"openshift-ovn-kubernetes\"  AND labels.pod.keyword: /ovnkube-node.*/ AND labels.container.keyword: \"nbdb\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "nbdb Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.namespace.keyword: \"openshift-ovn-kubernetes\"  AND labels.pod.keyword: /ovnkube-node.*/ AND labels.container.keyword: \"nbdb\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "northd CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.namespace.keyword: \"openshift-ovn-kubernetes\"  AND labels.pod.keyword: /ovnkube-node.*/ AND labels.container.keyword: \"northd\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "northd Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.namespace.keyword: \"openshift-ovn-kubernetes\"  AND labels.pod.keyword: /ovnkube-node.*/ AND labels.container.keyword: \"northd\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "sbdb CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.namespace.keyword: \"openshift-ovn-kubernetes\"  AND labels.pod.keyword: /ovnkube-node.*/ AND labels.container.keyword: \"sbdb\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "sbdb Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.namespace.keyword: \"openshift-ovn-kubernetes\"  AND labels.pod.keyword: /ovnkube-node.*/ AND labels.container.keyword: \"sbdb\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ovn-controller CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.namespace.keyword: \"openshift-ovn-kubernetes\"  AND labels.pod.keyword: /ovnkube-node.*/ AND labels.container.keyword: \"ovn-controller\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ovn-controller Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.namespace.keyword: \"openshift-ovn-kubernetes\"  AND labels.pod.keyword: /ovnkube-node.*/ AND labels.container.keyword: \"ovn-controller\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ovs-vswitchd CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{labels.node.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.node.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"ovsVswitchdCPU\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ovs-dbserver CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{labels.node.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.node.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"ovsdbServerCPU\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "ovs-rconn-discarded",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "max" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"ovsVswitchdRconnDiscarded\"",
     "timeField": "timestamp"
    },
    {
     "alias": "ovs-rconn-overflow",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "max" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"ovsVswitchdRconnOverflow\"",
     "timeField": "timestamp"
    },
    {
     "alias": "ovn-rconn-discarded",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "max" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"ovnControllerRconnDiscarded\"",
     "timeField": "timestamp"
    },
    {
     "alias": "ovn-rconn-overflow",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "max" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"ovnControllerRconnOverflow\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VswitchdStreamOpen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"ovsVswitchdStreamOpen\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "OVS flows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}-{{labels.bridge.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.bridge.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "labels.pod.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"ovsFlowsCounter\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ovn-controller flow generation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"ovnControllerFlowGeneration95Perc\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ovn-controller flow installation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"ovnControllerFlowInstallation95Perc\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "etcd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 },
   "collapsed": true,
   "panels": [
    {
     "title": "etcd 99th disk WAL fsync latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:4404",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"99thEtcdDiskWalFsyncDurationSeconds\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "etcd 99th disk backend commit latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:4404",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"99thEtcdDiskBackendCommitDurationSeconds\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Etcd leader changes",
     "type": "timeseries",
     "description": "sum(rate(etcd_server_leader_changes_seen_total[2m]))",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Etcd leader changes",
       "bucketAggs": [
        {
         "$$hashKey": "object:280",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:278",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: etcdLeaderChangesRate",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Etcd 99th network peer roundtrip time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "{{labels.pod.keyword}} to {{labels.To.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:806",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:322",
         "fake": true,
         "field": "labels.To.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:259",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:278",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: 99thEtcdRoundTripTimeSeconds",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Etcd resource utilization",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "Rss {{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: containerMemory* AND labels.container.keyword: etcd",
       "timeField": "timestamp"
      },
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: containerCPU* AND labels.container.keyword: etcd",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "API and Kubeproxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Only API request P99 latency - resource scoped",
     "type": "timeseries",
     "description": "histogram_quantile(0.99, sum(irate(apiserver_request_duration_seconds_bucket{apiserver=\"kube-apiserver\", verb=~\"LIST|GET\", subresource!~\"log|exec|portforward|attach|proxy\"}[2m])) by (le, resource, verb, scope))",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:1189",
         "fake": true,
         "field": "labels.verb.keyword",
         "id": "3",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "labels.resource.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:4301",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:4299",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: readOnlyAPICallsLatency AND labels.scope.keyword: resource",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Read Only API request P99 latency - namespace scoped",
     "type": "timeseries",
     "description": "histogram_quantile(0.99, sum(irate(apiserver_request_duration_seconds_bucket{apiserver=\"kube-apiserver\", verb=~\"LIST|GET\", subresource!~\"log|exec|portforward|attach|proxy\"}[2m])) by (le, resource, verb, scope))",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:1189",
         "fake": true,
         "field": "labels.verb.keyword",
         "id": "3",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:4301",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:4299",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: readOnlyAPICallsLatency AND labels.scope.keyword: namespace",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Read Only API request P99 latency - cluster scoped",
     "type": "timeseries",
     "description": "histogram_quantile(0.99, sum(irate(apiserver_request_duration_seconds_bucket{apiserver=\"kube-apiserver\", verb=~\"LIST|GET\", subresource!~\"log|exec|portforward|attach|proxy\"}[2m])) by (le, resource, verb, scope))",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:1189",
         "fake": true,
         "field": "labels.verb.keyword",
         "id": "3",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:4301",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:4299",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: readOnlyAPICallsLatency AND labels.scope.keyword: cluster",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Mutating API request P99 latency",
     "type": "timeseries",
     "description": "histogram_quantile(0.99, sum(irate(apiserver_request_duration_seconds_bucket{apiserver=\"kube-apiserver\", verb=~\"POST|PUT|DELETE|PATCH\", subresource!~\"log|exec|portforward|attach|proxy\"}[2m])) by (le, resource, verb, scope))",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:1189",
         "fake": true,
         "field": "labels.verb.keyword",
         "id": "3",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:4301",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:4299",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: mutatingAPICallsLatency",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "API request rate",
     "type": "timeseries",
     "description": "sum(irate(apiserver_request_total{apiserver=\"kube-apiserver\",verb!=\"WATCH\"}[2m])) by (verb,resource,code) > 0",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "alias": "{{labels.verb.keyword}} {{labels.resource.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:1855",
         "fake": true,
         "field": "labels.resource.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1189",
         "fake": true,
         "field": "labels.verb.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:4301",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:4299",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: APIRequestRate",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Kubelet & CRI-O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Kubelet process by CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:134",
         "fake": true,
         "field": "labels.node.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:61",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:59",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: kubeletCPU",
       "timeField": "timestamp"
      },
      {
       "alias": "Average across workers",
       "bucketAggs": [
        {
         "$$hashKey": "object:61",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:59",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: kubeletCPU",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Top 5 CRI-O process by CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:134",
         "fake": true,
         "field": "labels.node.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:61",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:59",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: crioCPU",
       "timeField": "timestamp"
      },
      {
       "alias": "Average across workers",
       "bucketAggs": [
        {
         "$$hashKey": "object:61",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:59",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: crioCPU",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Top 5 Kubelet RSS by memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "labels.node.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: kubeletMemory",
       "timeField": "timestamp"
      },
      {
       "alias": "Average across workers",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: kubeletMemory",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Top 5 CRI-O RSS by memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:134",
         "fake": true,
         "field": "labels.node.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:61",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:59",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: crioMemory",
       "timeField": "timestamp"
      },
      {
       "alias": "Average across workers",
       "bucketAggs": [
        {
         "$$hashKey": "object:61",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:59",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: crioMemory",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Master: $master",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 },
   "repeat": "master",
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU usage $master",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "labels.container.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.node.keyword: $master",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Container RSS memory $master",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "labels.container.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.node.keyword: $master",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "CPU $master",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{labels.mode.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:133",
         "fake": true,
         "field": "labels.mode.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": "_value*100",
         "meta": {},
         "settings": { "script": { "inline": "_value*100" } },
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeCPU-Masters\" AND labels.instance.keyword: $master",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Memory $master",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "Available",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryAvailable-Masters\" AND labels.instance.keyword: $master",
       "timeField": "timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryTotal-Masters\" AND labels.instance.keyword: $master",
       "timeField": "timestamp"
      },
      {
       "alias": "Utilization",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryUtilization-Masters\" AND labels.instance.keyword: $master",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Worker: $worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
   "repeat": "worker",
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU usage $worker",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "labels.container.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.node.keyword: $worker",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Container RSS memory $worker",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "labels.container.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: containerMemory AND labels.node.keyword: $worker",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "CPU aggregated workers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{labels.mode.keyword}}",
       "bucketAggs": [
        {
         "field": "labels.mode.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeCPU-AggregatedWorkers\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Memory $worker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "available",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryAvailable-Workers\" AND labels.instance.keyword: \"$worker\"",
       "timeField": "timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "offset": "" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryTotal-Workers\" AND labels.instance.keyword: $worker",
       "timeField": "timestamp"
      },
      {
       "alias": "Utilization",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "offset": "" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryUtilization-Workers\" AND labels.instance.keyword: $worker",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Aggregated worker nodes usage (only in aggregated metrics profile)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{labels.mode.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:133",
         "fake": true,
         "field": "labels.mode.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": "_value*100",
         "meta": {},
         "settings": { "script": { "inline": "_value*100" } },
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeCPU-AggregatedWorkers\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Avg Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "Available",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryAvailable-AggregatedWorkers\"",
       "timeField": "timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryTotal-AggregatedWorkers\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "container CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: containerCPU-AggregatedWorkers",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Container memory RSS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: containerMemory-AggregatedWorkers",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}